name: "Send Email after workflow"

on:
    workflow_dispatch:


jobs:
    send_email:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v2

            - name: "Setup python"
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'

            - name: "Install Dependencies"
              run: |
                python -m pip install --upgrade pip
                pip install python-dotenv

            - name: "Send mail by python script"
              run: python script.py
              env:
                # These are the secrets stored in GitHub
                SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
                SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
                RECIVER_EMAIL: ${{ secrets.RECIVER_EMAIL }}
                WORKFLOW_NAME: ${{ github.workflow }}  # Gets the name of the workflow
                REPO_NAME: ${{ github.repository }}    # Gets the name of the repo (owner/repo)
                WORKFLOW_RUN_ID: ${{ github.run_id }}  # Gets the unique run ID for the current workflow run_id